eHoliday/eHolidayBack/Controllers/CarController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using eHolidayService.Models;
using eHolidayService.ServiceContext;

namespace eHolidayBack.Controllers
{
    public class CarController : Controller
    {
        CarContext carContext = new CarContext();
        // GET
        public ActionResult Index()
        {
            var cars = carContext.FindAll();
            return View(cars);
        }
    }
}

eHoliday/eHolidayBack/Controllers/ClientController.cs
using System;
using System.Web.Mvc;
using eHolidayService.Models;
using eHolidayService.ServiceContext;

namespace eHolidayBack.Controllers
{
    public class ClientController : Controller
    {
        ClientContext clientContext = new ClientContext();
        // GET
        public ActionResult UpdateAdmin(int idclient)
        {
            clientContext.UpdateAdmin(idclient);

            return RedirectToAction("Dashboard", "Tours");
        }

        public ActionResult Connexion(string pseudo, string password)
        {
            Client auth = clientContext.FindByPseudoAndPassword(pseudo, password);

            Console.WriteLine(auth.Pseudo + " " + auth.Password);

            if (auth.Admin == 0)
            {
                Session["idClient"] = auth.Id;
                Session["pseudo"] = auth.Pseudo;
                Session["email"] = auth.Email;

                return RedirectToAction("Dashboard", "Tours");
            }
            else
            {
                string message = "Invalid informations. You are not an admnistrator";
                int status = 1;
                return RedirectToAction("Index", "Home", new {message = message, status = status});
            }
        }

        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }
    }
}

eHoliday/eHolidayBack/Controllers/HotelsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using eHolidayService.Models;
using eHolidayService.ServiceContext;

namespace eHolidayBack.Controllers
{
    public class HotelsController : Controller
    {
        HotelsContext hotelsContext = new HotelsContext();
        // GET
        public ActionResult Index()
        {
            var hotels = hotelsContext.FindAll();
            return View(hotels);
        }
    }
}

eHoliday/eHolidayBack/Controllers/VoyageController.cs
using eHolidayService.Models;
using eHolidayService.ServiceContext;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eHolidayBack.Controllers
{
    public class VoyageController : Controller
    {
        VoyageContext voyageContext = new VoyageContext();

        // GET: Voyage
        public ActionResult Index(int? page, int status = 0)
        {
            ViewBag.status = status;
            IPagedList<Voyage> voyages = voyageContext.FindAll().ToPagedList(page ?? 1, 3);

            return View(voyages);
        }

        public ActionResult Details(string idvoyage)
        {
            try
            {
                IPagedList<Voyage> voyages = voyageContext.FindAll().ToPagedList(1, 3);
                ViewBag.updatedvoyage = voyageContext.FindIncludeById(Convert.ToInt32(idvoyage));
                ViewBag.idvoyage = idvoyage;
                ViewBag.status = 1;

                return View("~/Views/Voyage/Index.cshtml", voyages);
            }catch(Exception e)
            {
                Console.WriteLine(e.Message);
                throw e;
            }
        }

        public ActionResult Update(string guest, string startDate, string EndDate, string idvoyage, string tourDuration, string tourPrice)
        {
            try
            {
                DateTime enddate = Convert.ToDateTime(startDate);
                DateTime startdate = Convert.ToDateTime(EndDate);
                int finalduration = Convert.ToInt32((enddate - startdate).TotalDays);
                voyageContext.Update(Convert.ToInt32(idvoyage), Convert.ToInt32(guest), startdate, enddate, Convert.ToInt32(tourDuration), 
                    Convert.ToInt32(tourPrice), finalduration);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw e;
            }
        }

        public ActionResult Delete(string idvoyage)
        {
            try
            {
                voyageContext.Delete(Convert.ToInt32(idvoyage));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw e;
            }
        }
    }
}

eHoliday/eHolidayBack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <link href="~/Assets/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Assets/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    @*<link href="~/Assets/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">*@
    <link href="~/Assets/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Assets/css/theme.css" rel="stylesheet" media="all">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src= "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="index.html">
                            @* <img src="~/Assets/images/icon/logo.png" alt="CoolAdmin"/> *@
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        </header>
        <!-- END HEADER MOBILE-->
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="~/Assets/images/icon/logo.png" alt="Cool Admin" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                            <a href="@Url.Action("Index", "Voyage")">Voyage</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Tours")">Tours</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Hotels")">Hotels</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Car")">Car</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            @*<form class="form-header" action="" method="POST">*@
                            <input class="au-input au-input--w300" type="text" name="search" id="search" placeholder="Search for datas &amp; reports..." />
                            <button id="btnSearch" class="au-btn--block" type="submit">
                                Search<i class="zmdi zmdi-search"></i>
                            </button>
                            @*</form>*@
                            <div class="content">
                                <a href="@Url.Action("Logout", "Client")">Logout</a>
                            </div>
                            <div class="header-button">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="~/Assets/images/icon/avatar-01.jpg" alt="John Doe" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">@Session["pseudo"]</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- HEADER DESKTOP-->
            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                            <p>Copyright © 2020 Narindra RANDRIANARISOA. All rights reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT-->
    <!-- END PAGE CONTAINER-->
    <!-- Jquery JS-->
    <script src="~/Assets/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/Assets/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Assets/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Assets/vendor/slick/slick.min.js">
    </script>
    <script src="~/Assets/vendor/wow/wow.min.js"></script>
    <script src="~/Assets/vendor/animsition/animsition.min.js"></script>
    <script src="~/Assets/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/Assets/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Assets/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/Assets/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Assets/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Assets/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Assets/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="~/Assets/js/main.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: "http://localhost:62149/SearchService.svc/GetPercentage",
                processData: false,
                dataType: "json",

                success: function (response) {
                    var percentageResult = response.GetPercentageResult;
                    console.log(response.GetPercentageResult)
                    var percent = [];
                    for (i = 0; i < percentageResult.length; i++) {
                        var value = percentageResult[i][0].Value;
                        console.log(value);
                        percent.push(value);
                    }
                    console.log(percent);
                    // Percent Chart
                    var ctx = document.getElementById("percent-chart");
                    if (ctx) {
                        ctx.height = 280;
                        var myChart = new Chart(ctx, {
                            type: 'doughnut',
                            data: {
                                datasets: [
                                    {
                                        label: "My First dataset",
                                        data: percent,
                                        backgroundColor: [
                                            '#00b5e9',
                                            '#fa4251',
                                            'rgba(0,173,95,0.9)',
                                            'rgb(228,179,10)',
                                            'rgb(228,132,147)'
                                        ],
                                        hoverBackgroundColor: [
                                            '#00b5e9',
                                            '#fa4251',
                                            'rgba(0,173,95,0.9)',
                                            'rgb(228,179,10)',
                                            'rgb(228,132,147)'
                                        ],
                                        borderWidth: [
                                            0, 0, 0, 0, 0
                                        ],
                                        hoverBorderColor: [
                                            'transparent',
                                            'transparent',
                                            'transparent',
                                            'transparent',
                                            'transparent'
                                        ]
                                    }
                                ],
                                labels: [
                                    'Excellent',
                                    'Satisfied',
                                    'Intermediate',
                                    'To Improve',
                                    'Disappointed'
                                ]
                            },
                            options: {
                                maintainAspectRatio: false,
                                responsive: true,
                                cutoutPercentage: 55,
                                animation: {
                                    animateScale: true,
                                    animateRotate: true
                                },
                                legend: {
                                    display: false
                                },
                                tooltips: {
                                    titleFontFamily: "Poppins",
                                    xPadding: 15,
                                    yPadding: 10,
                                    caretPadding: 0,
                                    bodyFontSize: 16
                                }
                            }
                        });
                    }
                },
                error: function (xhr, textStatus, error) {
                    console.log(xhr.responseText);
                    console.log(xhr.statusText);
                    console.log(textStatus);
                    console.log(error);
                }
            });
        };
    </script>
</body>
</html>

eHoliday/eHolidayBack/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <link href="~/Assets/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Assets/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    @*<link href="~/Assets/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">*@
    <link href="~/Assets/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Assets/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Assets/css/theme.css" rel="stylesheet" media="all">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

</head>

@RenderBody()
</html>